kotlin.code.style=official
android.useAndroidX=true
javax.net.ssl.trustStoreType=JKS
kotlin.incremental=false
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2560m"

# org.gradle.java.home=/path/to/java-25-openjdk
kotlin.compiler.execution.strategy=out-of-process

# Allow packaging with Homebrew OpenJDK
compose.desktop.packaging.checkJdkVendor=false

# App Versioning
app.version=1.0.0
app.version.code=1
